export const ROUTE_NAMES = {
  HOME: '/',
  STAFF: '/staff',
  ORGANIZATION: '/organizations',
  ACTIVITES: '/activities',
  POSITIONS: '/positions',
  POSITION: '/position/',
  DIVISION: '/divisions',
  CALENDAR: '/calendar',
  STAFFMEMBER: '/staff-member/',
  COMPANY: '/company/',
  ACTIVITY: '/activity/',
  CONTACTUS: '/contact-us',
  PROFILE: '/profile/',
  NEWACTIVITY: '/create-activity',
  ACTIVATEDEMAIL: '/activate/',
  RESETPASSWORD: '/reset-password/',
};
